[project]
name = "win-bc-controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bumble @ git+https://github.com/jchu634/bumble.git@345b0b6db4c571fb81d18279c02c02813f7a23ff",
    "inputs>=0.5",
    "pygame-ce>=2.5.6",
    "websockets>=15.0.1",
]
