[project]
name = "win-bc-controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bumble @ git+https://github.com/XenoKovah/bumble.git@3de16a3f9f42b983944a4b93af7d11cf908f8511",
    "inputs>=0.5",
    "pygame-ce>=2.5.6",
    "websockets>=15.0.1",
]
