# LMP basic opcodes
LMP_NAME_REQ = 1
LMP_NAME_RES = 2
LMP_ACCEPTED = 3
LMP_NOT_ACCEPTED = 4
LMP_CLKOFFSET_REQ = 5
LMP_CLKOFFSET_RES = 6
LMP_DETACH = 7
LMP_IN_RAND = 8
LMP_COMB_KEY = 9
LMP_UNIT_KEY = 10
LMP_AU_RAND = 11
LMP_SRES = 12
LMP_TEMP_RAND = 13
LMP_TEMP_KEY = 14
LMP_ENCRYPTION_MODE_REQ = 15
LMP_ENCRYPTION_KEY_SIZE_REQ = 16
LMP_START_ENCRYPTION_REQ = 17
LMP_STOP_ENCRYPTION_REQ = 18
LMP_SWITCH_REQ = 19
LMP_HOLD = 20
LMP_HOLD_REQ = 21
LMP_SNIFF_REQ = 23
LMP_UNSNIFF_REQ = 24
LMP_PARK_REQ = 25
LMP_SET_BROADCAST_SCAN_WINDOW = 27
LMP_MODIFY_BEACON = 28
LMP_UNPARK_BD_ADDR_REQ = 29
LMP_UNPARK_PM_ADDR_REQ = 30
LMP_INCR_POWER_REQ = 31
LMP_DECR_POWER_REQ = 32
LMP_MAX_POWER = 33
LMP_MIN_POWER = 34
LMP_AUTO_RATE = 35
LMP_PREFERRED_RATE = 36
LMP_VERSION_REQ = 37
LMP_VERSION_RES = 38
LMP_FEATURES_REQ = 39
LMP_FEATURES_RES = 40
LMP_QUALITY_OF_SERVICE = 41
LMP_QUALITY_OF_SERVICE_REQ = 42
LMP_SCO_LINK_REQ = 43
LMP_REMOVE_SCO_LINK_REQ = 44
LMP_MAX_SLOT = 45
LMP_MAX_SLOT_REQ = 46
LMP_TIMING_ACCURACY_REQ = 47
LMP_TIMING_ACCURACY_RES = 48
LMP_SETUP_COMPLETE = 49
LMP_USE_SEMI_PERMANENT_KEY = 50
LMP_HOST_CONNECTION_REQ = 51
LMP_SLOT_OFFSET = 52
LMP_PAGE_MODE_REQ = 53
LMP_PAGE_SCAN_MODE_REQ = 54
LMP_SUPERVISION_TIMEOUT = 55
LMP_TEST_ACTIVATE = 56
LMP_TEST_CONTROL = 57
LMP_ENCRYPTION_KEY_SIZE_MASK_REQ = 58
LMP_ENCRYPTION_KEY_SIZE_MASK_RES = 59
LMP_SET_AFH = 60
LMP_ENCAPSULATED_HEADER = 61
LMP_ENCAPSULATED_PAYLOAD = 62
LMP_SIMPLE_PAIRING_CONFIRM = 63
LMP_SIMPLE_PAIRING_NUMBER = 64
LMP_DHKEY_CHECK = 65
LMP_PAUSE_ENCRYPTION_AES_REQ = 66
LMP_MAX_DEFINED_OPCODE = 66
LMP_ESCAPE_124 = 124
LMP_ESCAPE_125 = 125
LMP_ESCAPE_126 = 126
LMP_ESCAPE_127 = 127

LMP_BASIC_OPCODE_NAMES = {
    LMP_NAME_REQ: "LMP_NAME_REQ",
    LMP_NAME_RES: "LMP_NAME_RES",
    LMP_ACCEPTED: "LMP_ACCEPTED",
    LMP_NOT_ACCEPTED: "LMP_NOT_ACCEPTED",
    LMP_CLKOFFSET_REQ: "LMP_CLKOFFSET_REQ",
    LMP_CLKOFFSET_RES: "LMP_CLKOFFSET_RES",
    LMP_DETACH: "LMP_DETACH",
    LMP_IN_RAND: "LMP_IN_RAND",
    LMP_COMB_KEY: "LMP_COMB_KEY",
    LMP_UNIT_KEY: "LMP_UNIT_KEY",
    LMP_AU_RAND: "LMP_AU_RAND",
    LMP_SRES: "LMP_SRES",
    LMP_TEMP_RAND: "LMP_TEMP_RAND",
    LMP_TEMP_KEY: "LMP_TEMP_KEY",
    LMP_ENCRYPTION_MODE_REQ: "LMP_ENCRYPTION_MODE_REQ",
    LMP_ENCRYPTION_KEY_SIZE_REQ: "LMP_ENCRYPTION_KEY_SIZE_REQ",
    LMP_START_ENCRYPTION_REQ: "LMP_START_ENCRYPTION_REQ",
    LMP_STOP_ENCRYPTION_REQ: "LMP_STOP_ENCRYPTION_REQ",
    LMP_SWITCH_REQ: "LMP_SWITCH_REQ",
    LMP_HOLD: "LMP_HOLD",
    LMP_HOLD_REQ: "LMP_HOLD_REQ",
    LMP_SNIFF_REQ: "LMP_SNIFF_REQ",
    LMP_UNSNIFF_REQ: "LMP_UNSNIFF_REQ",
    LMP_PARK_REQ: "LMP_PARK_REQ",
    LMP_SET_BROADCAST_SCAN_WINDOW: "LMP_SET_BROADCAST_SCAN_WINDOW",
    LMP_MODIFY_BEACON: "LMP_MODIFY_BEACON",
    LMP_UNPARK_BD_ADDR_REQ: "LMP_UNPARK_BD_ADDR_REQ",
    LMP_UNPARK_PM_ADDR_REQ: "LMP_UNPARK_PM_ADDR_REQ",
    LMP_INCR_POWER_REQ: "LMP_INCR_POWER_REQ",
    LMP_DECR_POWER_REQ: "LMP_DECR_POWER_REQ",
    LMP_MAX_POWER: "LMP_MAX_POWER",
    LMP_MIN_POWER: "LMP_MIN_POWER",
    LMP_AUTO_RATE: "LMP_AUTO_RATE",
    LMP_PREFERRED_RATE: "LMP_PREFERRED_RATE",
    LMP_VERSION_REQ: "LMP_VERSION_REQ",
    LMP_VERSION_RES: "LMP_VERSION_RES",
    LMP_FEATURES_REQ: "LMP_FEATURES_REQ",
    LMP_FEATURES_RES: "LMP_FEATURES_RES",
    LMP_QUALITY_OF_SERVICE: "LMP_QUALITY_OF_SERVICE",
    LMP_QUALITY_OF_SERVICE_REQ: "LMP_QUALITY_OF_SERVICE_REQ",
    LMP_SCO_LINK_REQ: "LMP_SCO_LINK_REQ",
    LMP_REMOVE_SCO_LINK_REQ: "LMP_REMOVE_SCO_LINK_REQ",
    LMP_MAX_SLOT: "LMP_MAX_SLOT",
    LMP_MAX_SLOT_REQ: "LMP_MAX_SLOT_REQ",
    LMP_TIMING_ACCURACY_REQ: "LMP_TIMING_ACCURACY_REQ",
    LMP_TIMING_ACCURACY_RES: "LMP_TIMING_ACCURACY_RES",
    LMP_SETUP_COMPLETE: "LMP_SETUP_COMPLETE",
    LMP_USE_SEMI_PERMANENT_KEY: "LMP_USE_SEMI_PERMANENT_KEY",
    LMP_HOST_CONNECTION_REQ: "LMP_HOST_CONNECTION_REQ",
    LMP_SLOT_OFFSET: "LMP_SLOT_OFFSET",
    LMP_PAGE_MODE_REQ: "LMP_PAGE_MODE_REQ",
    LMP_PAGE_SCAN_MODE_REQ: "LMP_PAGE_SCAN_MODE_REQ",
    LMP_SUPERVISION_TIMEOUT: "LMP_SUPERVISION_TIMEOUT",
    LMP_TEST_ACTIVATE: "LMP_TEST_ACTIVATE",
    LMP_TEST_CONTROL: "LMP_TEST_CONTROL",
    LMP_ENCRYPTION_KEY_SIZE_MASK_REQ: "LMP_ENCRYPTION_KEY_SIZE_MASK_REQ",
    LMP_ENCRYPTION_KEY_SIZE_MASK_RES: "LMP_ENCRYPTION_KEY_SIZE_MASK_RES",
    LMP_SET_AFH: "LMP_SET_AFH",
    LMP_ENCAPSULATED_HEADER: "LMP_ENCAPSULATED_HEADER",
    LMP_ENCAPSULATED_PAYLOAD: "LMP_ENCAPSULATED_PAYLOAD",
    LMP_SIMPLE_PAIRING_CONFIRM: "LMP_SIMPLE_PAIRING_CONFIRM",
    LMP_SIMPLE_PAIRING_NUMBER: "LMP_SIMPLE_PAIRING_NUMBER",
    LMP_DHKEY_CHECK: "LMP_DHKEY_CHECK",
    LMP_PAUSE_ENCRYPTION_AES_REQ: "LMP_PAUSE_ENCRYPTION_AES_REQ",
    LMP_ESCAPE_124: "LMP_ESCAPE_124",
    LMP_ESCAPE_125: "LMP_ESCAPE_125",
    LMP_ESCAPE_126: "LMP_ESCAPE_126",
    LMP_ESCAPE_127: "LMP_ESCAPE_127",
}

LMP_ACCEPTED_EXT = 1
LMP_FEATURES_REQ_EXT = 3
LMP_FEATURES_RES_EXT = 4
LMP_CHANNEL_CLASSIFICATION_REQ = 16
LMP_CHANNEL_CLASSIFICATION = 17
LMP_POWER_CONTROL_REQ = 31
LMP_POWER_CONTROL_RES = 32
LMP_LMP_ESCAPE_127_OPCODE_NAMES = {
    LMP_ACCEPTED_EXT: "LMP_ACCEPTED_EXT",
    LMP_FEATURES_REQ_EXT: "LMP_FEATURES_REQ_EXT",
    LMP_FEATURES_RES_EXT: "LMP_FEATURES_RES_EXT",
    LMP_CHANNEL_CLASSIFICATION_REQ: "LMP_CHANNEL_CLASSIFICATION_REQ",
    LMP_CHANNEL_CLASSIFICATION: "LMP_CHANNEL_CLASSIFICATION",
    LMP_POWER_CONTROL_REQ: "LMP_POWER_CONTROL_REQ",
    LMP_POWER_CONTROL_RES: "LMP_POWER_CONTROL_RES",
}


# Sizes are with the opcode excluded
# FIXME: ADD IN ANY OTHER OPCODES AS THEY BECOME SUPPORTED BY BTIDES!
LMP_BASIC_OPCODES_TO_BYTE_SIZES = {
    LMP_ACCEPTED: 1,
    LMP_NOT_ACCEPTED: 2,
    LMP_NAME_REQ: 16,
    LMP_NAME_RES: 16,
    LMP_VERSION_REQ: 5,
    LMP_VERSION_RES: 5,
    LMP_FEATURES_REQ: 8,
    LMP_FEATURES_RES: 8,
}
